### ISSUE TITLE
Rspec testing / mocking

### ISSUE THREAD

**Issue by daniellanciana** [restforce/restforce#334]
Hi, what is the best way of mocking Salesforce through Restforce for Rspec testing? Looking around the only framework I can see is https://github.com/execonline-inc/restforce_mock -- which doesn't have a lot of activity.

Any suggestions appreciated.

**Comment by timrogers** [comment]
Broadly, I'd say there are two approaches you could take to testing your integration: trusting Restforce, or not trusting Restforce.

### I trust Restforce: use standard RSpec stubbing and mocking

If you believe that Restforce is well-tested and fundamentally works, then using standard RSpec stubbing and mocking is simple. It's something you're likely to be doing already, and works well. 

All you need to do is set expectations or stubs on methods and have them return something you choose (probably a `double`). This is the approach I take. So it'd look something like this:

```ruby
expect(any_instance_of(Restforce::Client)).to receive(:update).with("Lead", name: "Acme plc").and_return(true)

allow(any_instance_of(Restforce::Client)).to receive(:find).with("Account", "salesforce_id_goes_here").and_return(double(Name:  "Acme plc"))
```

### I don't trust Restforce 😉 : use WebMock

If you're less sure about Restforce and want to give it a more thorough exercising (e.g. getting back real `Restforce::SObject` classes from queries, rather than test doubles), you could use [WebMock](https://github.com/bblimke/webmock) to build a kind of integration test. 

WebMock, instead of stubbing methods, lets you stub particular HTTP requests to return particular responses. This means that you change the behaviour at a lower level (the HTTP adapter, Faraday), but all of Restforce's code gets exercised and the tests are in some ways more realistic and end-to-end.

With it installed, you [just run `WebMock.allow_net_connect!` to disable requests to the internet](https://github.com/bblimke/webmock#real-requests-to-network-can-be-allowed-or-disabled). If you then run your tests, it'll very helpfully output the code you need to stub requests that are being made, along these lines:

```ruby
stub_request(:any, "www.example.com").to_return(body: "abc")
```

I hope that helps - if you have any further questions, just let me know!

**Comment by antwonlee** [comment]
@timrogers I think it will be good to have this in the document for everyone who implement TDD in their apps.
