### ISSUE TITLE
Very old version of `faraday` (v2.0.0) automatically installed when installing Restforce using Bundler

### ISSUE THREAD

**Issue by reedperkins** [restforce/restforce#901]
Hey there. Thanks for the library!

When trying to create a Restforce client i.e. 
```ruby 
client = Restforce.new(
  username: "your_username@example.com",
  password: "your_password",
  instance_url: "https://your_instance.salesforce.com",
  client_id: "your_client_id",
  client_secret: "your_client_secret",
  api_version: "57.0"
)
```
I get this error:
```
An attempt to run a request with a Faraday::Connection without adapter has been made. (RuntimeError)
Please set Faraday.default_adapter or provide one when initializing the connection.
```
It seems like there is an issue with the Faraday library
```
irb(main):012> Restforce.configuration.adapter
=> nil
irb(main):013> Faraday.default_adapter
=> nil
```
`Gemfile` contents: `gem 'restforce', '~> 7.4.0'`
`.ruby-versions` contents: `ruby-3.3.0`

When I checked `Gemfile.lock`, it looks like `faraday 2.0.0` was being installed. Adding `gem 'faraday', '2.10.0'` to my `Gemfile` and running `bundle install` fixes the issue, but it feels wrong to have to do that. Any insight as to what might be going on?

**Comment by timrogers** [comment]
Looks very similar to #898 - I wondering if allowing v2.11.0 will fix this and get it to install a better version 🤔

**Comment by reedperkins** [comment]
Thanks for the reply! Still new to ruby -- is there a reason `bundle` doesn't install the "highest" allowed version of `faraday` when installing `restforce`?

**Comment by timrogers** [comment]
I looked into this earlier and I think the answer is "it should be"!

I'm going to try to reproduce the issue and figure it out what's going on.

**Comment by timrogers** [comment]
I've just reproduced this - it's a very interesting problem! 🧠 

Installing the gem with `gem install` works as expected and installs the most recent supported `faraday` version, but when you use `bundle` and a Gemfile, it picks a very old version.

I think this could be a Bundler bug, so I will try raising it there.

## Installing with `gem install` works as expected (minimal reproduction)

```bash
$ docker run -it ubuntu /bin/bash -c "apt-get update && apt-get install -y ruby && gem install restforce"
```

```bash
# ...
Successfully installed faraday-2.10.1
```

## Installing with `bundle install` leads to surprising results (minimal reproduction)

```bash
$ docker run -it ubuntu /bin/bash -c "apt-get update && apt-get install -y ruby && gem install bundler && echo $'source \"https://rubygems.org\"\ngem \"restforce\"' > Gemfile && bundle"
```

```bash
# ...
Installing faraday 2.0.0
```

**Comment by timrogers** [comment]
RubyGems issue created here - I imagine there is going to be a simple explanation or my assumptions are wrong!

**Comment by reedperkins** [comment]
Awesome -- thanks for looking into this! I think you meant to attach a link in that last comment? I would love to follow that issue.

**Comment by deivid-rodriguez** [comment]
I provided an explanation for this at https://github.com/rubygems/rubygems/issues/8002#issuecomment-2328725079. Hopefully we can resolve this inconsistency between RubyGems and Bundler in the future!

**Comment by ccutrer** [comment]
Is there any chance restforce could relax its requirement on faraday to `< 3.a` instead of needing to update rest force for every single release of faraday? Faraday follows semver strictly, so it shouldn't lead to any broken APIs. There's _already_ a new version of Faraday (2.12.0) out that I can't update to. Out of 12 dependencies in my project that depend on Faraday, restforce is the only one that I have to wait for a new version of each and every time Faraday has a new release.

**Comment by timrogers** [comment]
I am open to doing that, but the reason I switched to the current approach is that there have been instances in the past where Faraday hasn't strictly followed semver, and that leads to bugs 😦 (I can't find the details on what exactly went wrong in the past though...)

**Comment by timrogers** [comment]
Previous example here: https://github.com/restforce/restforce/pull/701/files

**Comment by ccutrer** [comment]
I understand the hesitance. I've been burned by a patch release of Bundler breaking something -- but only in production. Unfortunately mistakes happen sometimes, especially when going through major refactors (as Faraday did from 1.x to 2.x). Hopefully projects learn from them, and avoid issues in the future.

The general consensus is that gems (libraries) have loose version dependencies in their gemspecs, and applications have tight dependencies by virtue of the lockfile (still relatively loose within the Gemfile itself). This is partly so that downstream dependencies (like applications!) aren't blocked when an upstream dependency is updated. This is even more important for security issues. It also relieves complex dependency graphs when not all intermediate dependencies allow concurrent versions of transitive dependencies (the Faraday 2.x upgrade in particular was quite difficult for us, since some gems supported by 1.x and 2.x at the same time, but many did not). Essentially each application developer can have the final say if a transitive dependency is updated or not.

If you're unwilling to loosen restforces's requirements on faraday, might I suggest that you subscribe to new release notifications of faraday on rubygems, so you can quickly test and then release a new version of restforce that allows the newer version of faraday? At the least, perhaps loosen it to allow new patch versions of faraday by default, but not new minor versions? I'd hate for a security issue to come up in faraday and be caught deciding if I temporarily fork restforce in order to be able to resolve a security issue.

**Comment by januszm** [comment]
It still downgrades faraday to 2.0
